# **One Hot Encoding**

It is a technique used to convert categorical data(nominal) into numeric data. It must be used on the nominal data as when your data have not specific order.

In [44]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [45]:
df = pd.read_csv("data/titanic.csv", usecols=["Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"])
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df["Age"] = df["Age"].fillna(df["Age"].mean())

X = df.drop(columns=["Survived"])
y = df["Survived"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

<br>

# **One hot encoding using Pandas**

In [46]:
pd.get_dummies(df, columns=["Sex", "Embarked"], dtype=int)

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.000000,1,0,7.2500,0,1,0,0,1
1,1,1,38.000000,1,0,71.2833,1,0,1,0,0
2,1,3,26.000000,0,0,7.9250,1,0,0,0,1
3,1,1,35.000000,1,0,53.1000,1,0,0,0,1
4,0,3,35.000000,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,0,1,0,0,1
887,1,1,19.000000,0,0,30.0000,1,0,0,0,1
888,0,3,29.699118,1,2,23.4500,1,0,0,0,1
889,1,1,26.000000,0,0,30.0000,0,1,1,0,0
890,0,3,32.000000,0,0,7.7500,0,1,0,1,0

In [47]:
# droping the first column

pd.get_dummies(df, columns=["Sex", "Embarked"], dtype=int, drop_first=True)

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.000000,1,0,7.2500,1,0,1
1,1,1,38.000000,1,0,71.2833,0,0,0
2,1,3,26.000000,0,0,7.9250,0,0,1
3,1,1,35.000000,1,0,53.1000,0,0,1
4,0,3,35.000000,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,1,0,1
887,1,1,19.000000,0,0,30.0000,0,0,1
888,0,3,29.699118,1,2,23.4500,0,0,1
889,1,1,26.000000,0,0,30.0000,1,0,0
890,0,3,32.000000,0,0,7.7500,1,1,0

<br>

# **One hot encoding using sklearn**

In [48]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, dtype=int, drop="first")

encoder.fit(X_train[["Sex", "Embarked"]])

OneHotEncoder(drop='first', dtype=<class 'int'>, sparse_output=False)

In [49]:
encoder.get_feature_names_out().tolist()

['Sex_male', 'Embarked_Q', 'Embarked_S']

In [58]:
X_train[encoder.get_feature_names_out()]=encoder.transform(X_train[["Sex", "Embarked"]])
X_test[encoder.get_feature_names_out()]=encoder.transform(X_test[["Sex", "Embarked"]])

In [59]:
X_train.sample(5)

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex_male,Embarked_Q,Embarked_S
456,1,male,65.000000,0,0,26.5500,S,1,0,1
151,1,female,22.000000,1,0,66.6000,S,0,0,1
245,1,male,44.000000,2,0,90.0000,Q,1,1,0
496,1,female,54.000000,1,0,78.2667,C,0,0,0
201,3,male,29.699118,8,2,69.5500,S,1,0,1

In [60]:
X_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Sex_male,Embarked_Q,Embarked_S
709,3,male,29.699118,1,1,15.2458,C,1,0,0
439,2,male,31.000000,0,0,10.5000,S,1,0,1
840,3,male,20.000000,0,0,7.9250,S,1,0,1
720,2,female,6.000000,0,1,33.0000,S,0,0,1
39,3,female,14.000000,1,0,11.2417,C,0,0,0
...,...,...,...,...,...,...,...,...,...,...
433,3,male,17.000000,0,0,7.1250,S,1,0,1
773,3,male,29.699118,0,0,7.2250,C,1,0,0
25,3,female,38.000000,1,5,31.3875,S,0,0,1
84,2,female,17.000000,0,0,10.5000,S,0,0,1
10,3,female,4.000000,1,1,16.7000,S,0,0,1