In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_csv("data/titanic.csv").drop(columns=["PassengerId", "Ticket", "Cabin", "Name"])

In [61]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [62]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer

X = df.drop(columns=["Survived"])
y = df["Survived"]

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42)

In [63]:
line = Pipeline(steps=[
    ("scale", StandardScaler()),
    ("impute", KNNImputer(n_neighbors=5, weights="uniform"))
])

In [64]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [ ]:
t = ColumnTransformer(transformers=[
    ("transform", line, ["Fare", "Age"])
], remainder="passthrough")

In [66]:
# t.fit(X_train)
X_train = pd.DataFrame(t.fit_transform(X_train), columns=t.get_feature_names_out())
X_test = pd.DataFrame(t.fit_transform(X_test), columns=t.get_feature_names_out())

In [67]:
X_train.head()

,transform__Fare,transform__Age,remainder__Pclass,remainder__Sex,remainder__SibSp,remainder__Parch,remainder__Embarked
0,-0.078684,1.104489,1,male,0,0,S
1,-0.377145,-0.448587,2,male,0,0,S
2,-0.474867,0.172644,3,male,0,0,S
3,-0.47623,-0.24151,3,male,1,0,S
4,-0.025249,-1.622022,3,female,4,2,S

In [68]:
X_train.isna().sum()

transform__Fare        0
transform__Age         0
remainder__Pclass      0
remainder__Sex         0
remainder__SibSp       0
remainder__Parch       0
remainder__Embarked    2
dtype: int64