# **Iterative Imputation**

Iterative imputation fills missing values by repeatedly using a machine learning model to predict them from other features. It is basically for numeric and we dont need to scale the data for iterative imputation.

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv("data/titanic.csv").drop(columns=["PassengerId", "Ticket", "Cabin", "Name"])
df["Family"] = df["SibSp"]+df["Parch"]

In [20]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Family        0
dtype: int64

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.experimental import enable_iterative_imputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import IterativeImputer

X = df.drop(columns=["Survived"])
y = df["Survived"]

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
X_train.isna().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
Family        0
dtype: int64

In [23]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Family
331       1    male  45.5      0      0  28.5000        S       0
733       2    male  23.0      0      0  13.0000        S       0
382       3    male  32.0      0      0   7.9250        S       0
704       3    male  26.0      1      0   7.8542        S       1
813       3  female   6.0      4      2  31.2750        S       6

In [24]:
t = ColumnTransformer(transformers=[
    ("transform", IterativeImputer(), ["Fare", "Age", "Family"])
], remainder="passthrough")

In [25]:
# t.fit(X_train)
X_train = pd.DataFrame(t.fit_transform(X_train), columns=t.get_feature_names_out())
X_test = pd.DataFrame(t.fit_transform(X_test), columns=t.get_feature_names_out())

In [26]:
X_train.head()

,transform__Fare,transform__Age,transform__Family,remainder__Pclass,remainder__Sex,remainder__SibSp,remainder__Parch,remainder__Embarked
0,28.5,45.5,0.0,1,male,0,0,S
1,13.0,23.0,0.0,2,male,0,0,S
2,7.925,32.0,0.0,3,male,0,0,S
3,7.8542,26.0,1.0,3,male,1,0,S
4,31.275,6.0,6.0,3,female,4,2,S

In [27]:
X_train.isna().sum()

transform__Fare        0
transform__Age         0
transform__Family      0
remainder__Pclass      0
remainder__Sex         0
remainder__SibSp       0
remainder__Parch       0
remainder__Embarked    2
dtype: int64